# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\chord.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ChordWindow(object):
    def setupUi(self, ChordWindow):
        ChordWindow.setObjectName(_fromUtf8("ChordWindow"))
        ChordWindow.resize(665, 470)
        ChordWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(ChordWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.search_box = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_box.sizePolicy().hasHeightForWidth())
        self.search_box.setSizePolicy(sizePolicy)
        self.search_box.setObjectName(_fromUtf8("search_box"))
        self.verticalLayout.addWidget(self.search_box)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.source_box = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_box.sizePolicy().hasHeightForWidth())
        self.source_box.setSizePolicy(sizePolicy)
        self.source_box.setObjectName(_fromUtf8("source_box"))
        self.source_box.addItem(_fromUtf8(""))
        self.source_box.addItem(_fromUtf8(""))
        self.source_box.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.source_box)
        self.search_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn.sizePolicy().hasHeightForWidth())
        self.search_btn.setSizePolicy(sizePolicy)
        self.search_btn.setObjectName(_fromUtf8("search_btn"))
        self.horizontalLayout.addWidget(self.search_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.song_list_box = QtGui.QListWidget(self.centralwidget)
        self.song_list_box.setObjectName(_fromUtf8("song_list_box"))
        self.verticalLayout.addWidget(self.song_list_box)
        ChordWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(ChordWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ChordWindow.setStatusBar(self.statusbar)
        self.chord_dock = QtGui.QDockWidget(ChordWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chord_dock.sizePolicy().hasHeightForWidth())
        self.chord_dock.setSizePolicy(sizePolicy)
        self.chord_dock.setMinimumSize(QtCore.QSize(450, 450))
        self.chord_dock.setObjectName(_fromUtf8("chord_dock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.flat_btn = QtGui.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flat_btn.sizePolicy().hasHeightForWidth())
        self.flat_btn.setSizePolicy(sizePolicy)
        self.flat_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.flat_btn.setObjectName(_fromUtf8("flat_btn"))
        self.horizontalLayout_3.addWidget(self.flat_btn)
        self.sharp_btn = QtGui.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sharp_btn.sizePolicy().hasHeightForWidth())
        self.sharp_btn.setSizePolicy(sizePolicy)
        self.sharp_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.sharp_btn.setObjectName(_fromUtf8("sharp_btn"))
        self.horizontalLayout_3.addWidget(self.sharp_btn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.easy_chord_btn = QtGui.QPushButton(self.dockWidgetContents_2)
        self.easy_chord_btn.setObjectName(_fromUtf8("easy_chord_btn"))
        self.gridLayout.addWidget(self.easy_chord_btn, 0, 4, 1, 1)
        self.line = QtGui.QFrame(self.dockWidgetContents_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.chord_box = QtGui.QTextEdit(self.dockWidgetContents_2)
        self.chord_box.setObjectName(_fromUtf8("chord_box"))
        self.gridLayout.addWidget(self.chord_box, 1, 0, 1, 5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.font_size_box = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font_size_box.sizePolicy().hasHeightForWidth())
        self.font_size_box.setSizePolicy(sizePolicy)
        self.font_size_box.setDecimals(0)
        self.font_size_box.setMinimum(8.0)
        self.font_size_box.setProperty("value", 8.0)
        self.font_size_box.setObjectName(_fromUtf8("font_size_box"))
        self.horizontalLayout_4.addWidget(self.font_size_box)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.dockWidgetContents_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 3, 1, 1)
        self.save_btn = QtGui.QPushButton(self.dockWidgetContents_2)
        self.save_btn.setObjectName(_fromUtf8("save_btn"))
        self.gridLayout.addWidget(self.save_btn, 2, 0, 1, 5)
        self.chord_box.raise_()
        self.easy_chord_btn.raise_()
        self.save_btn.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.chord_dock.setWidget(self.dockWidgetContents_2)
        ChordWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.chord_dock)

        self.retranslateUi(ChordWindow)
        QtCore.QMetaObject.connectSlotsByName(ChordWindow)

    def retranslateUi(self, ChordWindow):
        ChordWindow.setWindowTitle(_translate("ChordWindow", "MainWindow", None))
        self.source_box.setItemText(0, _translate("ChordWindow", "hopam.vn", None))
        self.source_box.setItemText(1, _translate("ChordWindow", "hopamchuan.com", None))
        self.source_box.setItemText(2, _translate("ChordWindow", "hopamviet.com", None))
        self.search_btn.setText(_translate("ChordWindow", "Tìm Kiếm", None))
        self.chord_dock.setWindowTitle(_translate("ChordWindow", "Hợp Âm", None))
        self.label_2.setText(_translate("ChordWindow", "Đổi Tông", None))
        self.flat_btn.setText(_translate("ChordWindow", "b", None))
        self.sharp_btn.setText(_translate("ChordWindow", "#", None))
        self.easy_chord_btn.setText(_translate("ChordWindow", "Hợp Âm Dễ", None))
        self.label.setText(_translate("ChordWindow", "Kích Cỡ Chữ", None))
        self.save_btn.setText(_translate("ChordWindow", "Lưu", None))

